<!doctype html><html lang=cn><head><meta charset=utf-8><meta http-equiv=x-ua-compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1"><meta name=referrer content="no-referrer"><link rel=dns-prefetch href=https://i.geekbank.cf/><title>深入理解Java中异常体系 | 极客快訊</title><meta property="og:title" content="深入理解Java中异常体系 - 极客快訊"><meta property="og:type" content="article"><meta property="og:locale" content="cn"><meta property="og:image" content="https://p1.pstatp.com/large/pgc-image/a9c3c726681446dbae0fb73628403311"><link rel=alternate hreflang=x-default href=https://geekbank.cf/tw/%e7%a7%91%e6%8a%80/31ae78ae.html><link rel=alternate hreflang=zh-tw href=https://geekbank.cf/tw/%e7%a7%91%e6%8a%80/31ae78ae.html><link rel=alternate hreflang=zh-cn href=https://geekbank.cf/cn/%e7%a7%91%e6%8a%80/31ae78ae.html><link rel=alternate hreflang=zh-hk href=https://geekbank.cf/tw/%e7%a7%91%e6%8a%80/31ae78ae.html><link rel=alternate hreflang=zh-mo href=https://geekbank.cf/tw/%e7%a7%91%e6%8a%80/31ae78ae.html><link rel=alternate hreflang=zh-my href=https://geekbank.cf/cn/%e7%a7%91%e6%8a%80/31ae78ae.html><link rel=alternate hreflang=zh-sg href=https://geekbank.cf/cn/%e7%a7%91%e6%8a%80/31ae78ae.html><link rel=canonical href=https://geekbank.cf/tw/%e7%a7%91%e6%8a%80/31ae78ae.html><meta property="article:published_time" content="2020-11-14T21:06:59+08:00"><meta property="article:modified_time" content="2020-11-14T21:06:59+08:00"><meta name=Keywords content><meta name=description content="深入理解Java中异常体系"><meta name=author content="极客快訊"><meta property="og:url" content="/cn/%E7%A7%91%E6%8A%80/31ae78ae.html"><link rel=apple-touch-icon sizes=180x180 href=../../apple-touch-icon.png><link rel=icon type=image/png sizes=32x32 href=../../favicon-32x32.png><link rel=icon type=image/png sizes=16x16 href=../../favicon-16x16.png><link rel=manifest href=../../site.webmanifest><link rel=mask-icon href=../../safari-pinned-tab.svg color=#5bbad5><meta name=msapplication-TileColor content="#ffc40d"><meta name=theme-color content="#ffffff"><link rel=stylesheet href=https://geekbank.cf/css/normalize.css><link rel=stylesheet href=https://geekbank.cf/css/style.css><script type=text/javascript src=https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js></script><script type=text/javascript src=https://geekbank.cf/js/jqthumb.min.js></script><script data-ad-client=ca-pub-3525055026201463 async src=https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js></script></head><body><header id=header class=clearfix><div class=container><div class=col-group><div class=site-name><h1><a id=logo href>🤓 极客快讯 Geek Bank</a></h1><p class=description>为你带来最全的科技知识 🧡</p></div><div><nav id=nav-menu class=clearfix><a class=current href>猜你喜歡</a>
<a href=../../tw/categories/%E7%A7%91%E6%8A%80.html title=科技>科技</a>
<a href=../../tw/categories/%E9%81%8A%E6%88%B2.html title=遊戲>遊戲</a>
<a href=../../tw/categories/%E7%A7%91%E5%AD%B8.html title=科學>科學</a></nav></div></div></div></header><div id=body><div class=container><div class=col-group><div class=col-8 id=main><div class=res-cons><article class=post><header><h1 class=post-title>深入理解Java中异常体系</h1></header><date class="post-meta meta-date">2020-11-14</date><div class=post-meta><span>|</span>
<span class=meta-category><a href=cn/categories/%E7%A7%91%E6%8A%80.html>科技</a></span></div><div class=post-content><h1 class=title-article><br></h1><p>任何程序都追求正确有效的运行，除了保证我们代码尽可能的少出错之外，我们还要考虑如何有效的处理异常，一个良好的异常框架对于系统来说是至关重要的。最近在给公司写采集框架的时候系统的了解一边，收获颇多，特此记录相关的理论。</p><p>1 .异常体系简介：</p><p>异常是指由于各种不期而至的情况，导致程序中断运行的一种指令流,如：文件找不到、非法参数、网络超时等。为了保证正序正常运行，在设计程序时必须考虑到各种异常情况，并正确的对异常进行处理。异常也是一种对象，java当中定义了许多异常类，并且定义了基类java.lang.Throwable作为所有异常的超类。Java语言设计者将异常划分为两类：Error和Exception，其体系结构大致如下图所示：</p><div class=pgc-img><img alt=深入理解Java中异常体系 onerror=errorimg.call(this); src=https://p1.pstatp.com/large/pgc-image/a9c3c726681446dbae0fb73628403311><p class=pgc-img-caption></p></div><p></p><p>Throwable：有两个重要的子类：Exception（异常）和Error（错误），两者都包含了大量的异常处理类。</p><p>1、Error（错误）：是程序中无法处理的错误，表示运行应用程序中出现了严重的错误。此类错误一般表示代码运行时JVM出现问题。通常有Virtual MachineError（虚拟机运行错误）、NoClassDefFoundError（类定义错误）等。比如说当jvm耗完可用内存时，将出现OutOfMemoryError。此类错误发生时，JVM将终止线程。</p><p>这些错误是不可查的，非代码性错误。因此，当此类错误发生时，应用不应该去处理此类错误。</p><p>2、Exception（异常）：程序本身可以捕获并且可以处理的异常。</p><p><br></p><p>Exception这种异常又分为两类：运行时异常和编译异常。</p><p>1、运行时异常(不受检异常)：RuntimeException类极其子类表示JVM在运行期间可能出现的错误。比如说试图使用空值对象的引用（NullPointerException）、数组下标越界（ArrayIndexOutBoundException）。此类异常属于不可查异常，一般是由程序逻辑错误引起的，在程序中可以选择捕获处理，也可以不处理。</p><p>2、编译异常(受检异常)：Exception中除RuntimeException极其子类之外的异常。如果程序中出现此类异常，比如说IOException，必须对该异常进行处理，否则编译不通过。在程序中，通常不会自定义该类异常，而是直接使用系统提供的异常类。</p><p><br></p><p>可查异常与不可查异常：java的所有异常可以分为可查异常（checked exception）和不可查异常（unchecked exception）。</p><p>1、可查异常：编译器要求必须处理的异常。正确的程序在运行过程中，经常容易出现的、符合预期的异常情况。一旦发生此类异常，就必须采用某种方式进行处理。除RuntimeException及其子类外，其他的Exception异常都属于可查异常。编译器会检查此类异常，也就是说当编译器检查到应用中的某处可能会此类异常时，将会提示你处理本异常——要么使用try-catch捕获，要么使用throws语句抛出，否则编译不通过。</p><p>2、不可查异常：编译器不会进行检查并且不要求必须处理的异常，也就说当程序中出现此类异常时，即使我们没有try-catch捕获它，也没有使用throws抛出该异常，编译也会正常通过。该类异常包括运行时异常（RuntimeException极其子类）和错误（Error）。</p><p><br></p><p>2.异常处理流程：</p><p></p><p>在java应用中，异常的处理机制分为抛出异常和捕获异常。</p><p>抛出异常：当一个方法出现错误而引发异常时，该方法会将该异常类型以及异常出现时的程序状态信息封装为异常对象，并交给本应用。运行时，该应用将寻找处理异常的代码并执行。任何代码都可以通过throw关键词抛出异常，比如java源代码抛出异常、自己编写的代码抛出异常等。</p><p>捕获异常：一旦方法抛出异常，系统自动根据该异常对象寻找合适异常处理器（Exception Handler）来处理该异常。所谓合适类型的异常处理器指的是异常对象类型和异常处理器类型一致。</p><p></p><p>对于不同的异常，java采用不同的异常处理方式：</p><p>1、运行异常将由系统自动抛出，应用本身可以选择处理或者忽略该异常。</p><p>2、对于方法中产生的Error，该异常一旦发生JVM将自行处理该异常，因此java允许应用不抛出此类异常。</p><p>3、对于所有的可查异常，必须进行捕获或者抛出该方法之外交给上层处理。也就是当一个方法存在异常时，要么使用try-catch捕获，要么使用该方法使用throws将该异常抛调用该方法的上层调用者。</p><p><br></p><p>2.1捕获异常</p><p>1、try-catch语句</p><p><strong>try</strong> {</p><p>//可能产生的异常的代码区，也成为监控区</p><p>}<strong>catch</strong> (ExceptionType1 e) {</p><p>//捕获并处理try抛出异常类型为ExceptionType1的异常</p><p>}<strong>catch</strong>(ExceptionType2 e) {</p><p>//捕获并处理try抛出异常类型为ExceptionType2的异常</p><p>}</p><p></p><p>监控区一旦发生异常，则会根据当前运行时的信息创建异常对象，并将该异常对象抛出监控区，同时</p><p>系统根据该异常对象依次匹配catch子句，若匹配成功（抛出的异常对象的类型和catch子句的异常类的类型或者是该异常类的子类的类型一致），则运行其中catch代码块中的异常处理代码，一旦处理结束，那就意味着整个try-catch结束。含有多个catch子句，一旦其中一个catch子句与抛出的异常对象类型一致时，其他catch子句将不再有匹配异常对象的机会。</p><p><br></p><p>2、try-catch-finally</p><p><strong>try {</strong></p><p>//可能产生的异常的代码区</p><p>}catch (ExceptionType1 e) {</p><p>//捕获并处理try抛出异常类型为ExceptionType1的异常</p><p>}catch (ExceptionType2 e){</p><p>//捕获并处理try抛出异常类型为ExceptionType2的异常</p><p>}finally{</p><p>//无论是出现异常，finally块中的代码都将被执行</p><p>}</p><p><br></p><p>3、try-catch-finally代码块的执行顺序：</p><p>A)try没有捕获异常时，try代码块中的语句依次被执行，跳过catch。如果存在finally则执行finally代码块，否则执行后续代码。</p><p>B）try捕获到异常时，如果没有与之匹配的catch子句，则该异常交给JVM处理。如果存在finally，则其中的代码仍然被执行，但是finally之后的代码不会被执行。</p><p>C）try捕获到异常时，如果存在与之匹配的catch，则跳到该catch代码块执行处理。如果存在finally则执行finally代码块，执行完finally代码块之后继续执行后续代码；否则直接执行后续代码。另外注意，try代码块出现异常之后的代码不会被执行。（见下图：）</p><p></p><div class=pgc-img><img alt=深入理解Java中异常体系 onerror=errorimg.call(this); src=https://p3.pstatp.com/large/pgc-image/ca0d8f52970f4e0e970c5c74a7ca2608><p class=pgc-img-caption></p></div><p>4、总结</p><p>try代码块：用于捕获异常。其后可以接零个或者多个catch块。如果没有catch块，后必须跟finally块，来完成资源释放等操作，另外建议不要在finally中使用return，不用尝试通过catch来控制代码流程。</p><p>catch代码块：用于捕获异常，并在其中处理异常。</p><p>finally代码块：无论是否捕获异常，finally代码总会被执行。如果try代码块或者catch代码块中有return语句时，finally代码块将在方法返回前被执行。注意以下几种情况，finally代码块不会被执行：</p><p>1、 在前边的代码中使用System.exit()退出应用。</p><p>2、 程序所在的线程死亡或者cpu关闭</p><p>3、 如果在finally代码块中的操作又产生异常，则该finally代码块不能完全执行结束，同时该异常会覆盖前边抛出的异常。</p><p><br></p><p>2.2抛出异常</p><p>1、throws抛出异常</p><p>如果一个方法可能抛出异常，但是没有能力处理该异常或者需要通过该异常向上层汇报处理结果，可以在方法声明时使用throws来抛出异常。这就相当于计算机硬件发生损坏，但是计算机本身无法处理，就将该异常交给维修人员来处理。</p><p>publicmethodName throws Exception1,Exception2….(params){}</p><p>其中Exception1,Exception2…为异常列表一旦该方法中某行代码抛出异常，则该异常将由调用该方法的上层方法处理。如果上层方法无法处理，可以继续将该异常向上层抛。</p><p>2、throw抛出异常</p><p>在方法内，用throw来抛出一个Throwable类型的异常。一旦遇到到throw语句，后面的代码将不被执行。然后，便是进行异常处理——包含该异常的try-catch最终处理，也可以向上层抛出。注意我们只能抛出Throwable类和其子类的对象。</p><p></p><p>throw newExceptionType;</p><p></p><p>比如我们可以抛出：throw new Exception();</p><p>也有时候我们也需要在catch中抛出异常,这也是允许的，比如说：</p><p></p><p>Try{</p><p>//可能会发生异常的代码</p><p>}catch(Exceptione){</p><p>throw newException(e);</p><p>}</p><p></p><p>3、异常关系链</p><p>在实际开发过程中经常在捕获一个异常之后抛出另外一个异常，并且我们希望在新的异常对象中保存原始异常对象的信息，实际上就是异常传递，即把底层的异常对象传给上层，一级一级，逐层抛出。当程序捕获了一个底层的异常，而在catch处理异常的时候选择将该异常抛给上层…这样异常的原因就会逐层传递，形成一个由低到高的异常链。但是异常链在实际应用中一般不建议使用，同时异常链每次都需要就将原始的异常对象封装为新的异常对象，消耗大量资源。现在（jdk 1.4之后）所有的Throwable的子类构造中都可以接受一个cause对象，这个cause也就是原始的异常对象。</p><p>下面是一个不错的例子：</p><pre><code>/*</code></pre><pre><code> *高层异常</code></pre><pre><code> */</code></pre><pre><code>classHighLevelExceptionextends Exception{</code></pre><pre><code>   public HighLevelException(Throwable cause) {</code></pre><pre><code>      super(cause);</code></pre><pre><code>   }</code></pre><pre><code>}</code></pre><pre><code>/*</code></pre><pre><code> *中层异常</code></pre><pre><code> */</code></pre><pre><code>classMiddleLevelExceptionextends Exception{</code></pre><pre><code>   public MiddleLevelException(Throwable cause) {</code></pre><pre><code>      super(cause);</code></pre><pre><code>   }</code></pre><pre><code>}</code></pre><pre><code>/*</code></pre><pre><code> *底层异常</code></pre><pre><code> */</code></pre><pre><code>classLowLevelExceptionextends Exception{</code></pre><pre><code>}</code></pre><pre><code>publicclass TestException {</code></pre><pre><code> </code></pre><pre><code>   publicvoid highLevelAccess()throws HighLevelException{</code></pre><pre><code>      try {</code></pre><pre><code>          middleLevelAccess();</code></pre><pre><code>      }catch (Exception e) {</code></pre><pre><code>          thrownew HighLevelException(e);</code></pre><pre><code>      }</code></pre><pre><code>   }</code></pre><pre><code>   </code></pre><pre><code>   publicvoid middleLevelAccess()throws MiddleLevelException{</code></pre><pre><code>      try {</code></pre><pre><code>          lowLevelAccess();</code></pre><pre><code>      }catch (Exception e) {</code></pre><pre><code>          thrownew MiddleLevelException(e);</code></pre><pre><code>      }</code></pre><pre><code>   }</code></pre><pre><code> </code></pre><pre><code>   publicvoid lowLevelAccess()throws LowLevelException {</code></pre><pre><code>      thrownew LowLevelException();</code></pre><pre><code>   }</code></pre><pre><code> </code></pre><pre><code>   publicstaticvoid main(String[] args) {</code></pre><pre><code>      /*</code></pre><pre><code>       * lowlevelAccess()将异常对象抛给middleLevelAccess()，而</code></pre><pre><code>       * middleLevelAccess()又将异常对象抛给highLevelAccess(),</code></pre><pre><code>       *也就是底层的异常对象一层层传递给高层。最终在在高层可以获得底层的异常对象。</code></pre><pre><code>       */</code></pre><pre><code>      try {</code></pre><pre><code>          new TestException().highLevelAccess();</code></pre><pre><code>      }catch (HighLevelException e) {</code></pre><pre><code>          e.printStackTrace();</code></pre><pre><code>          System.out.println(e.getCause());</code></pre><pre><code>      }</code></pre><pre><code>   }</code></pre><pre><code>}</code></pre><p><br></p><p>4、异常转译</p><p>异常转义就是将一种类型的异常转成另一种类型的异常，然后再抛出异常。之所以要进行转译，是为了更准确的描述异常。就我个人而言，我更喜欢称之为异常类型转换。在实际应用中，为了构建自己的日志系统，经常需要把系统的一些异常信息描述成我们想要的异常信息，就可以使用异常转译。异常转译针对所有Throwable类的子类而言，其子类型都可以相互转换。</p><p>通常而言，更为合理的转换方式是：</p><p>1、 Error——>Exception</p><p>2、 Error——>RuntimeException</p><p>3、 Exception——>RuntimeException,</p><p>在下面的代码中，我们自定义了MyException异常类，然后我们将IOException类型的异常转为MyException类型的异常，最后抛出。</p><pre><code>class MyExceptionextends Exception {</code></pre><pre><code>   public MyException(String msg, Throwable e) {</code></pre><pre><code>      super(msg, e);</code></pre><pre><code>   }</code></pre><pre><code>}</code></pre><pre><code> </code></pre><pre><code>publicclass Demo {</code></pre><pre><code>   publicstaticvoid main(String[] args)throws MyException {</code></pre><pre><code>      Filefile =new File("H:/test.txt");</code></pre><pre><code>      if (file.exists())</code></pre><pre><code>          try {</code></pre><pre><code>             file.createNewFile();</code></pre><pre><code>          }catch (IOException e) {</code></pre><pre><code>             thrownew MyException("文件创建失败！", e);</code></pre><pre><code>          }</code></pre><pre><code>   }</code></pre><pre><code> </code></pre><pre><code>}</code></pre><p>5、Throwable类中常用的方法</p><p>像catch(Exception e)中的Exception就是异常的变量类型，e则是形参。通常在进行异常输出时有如下几个方法可用：</p><p>e.getCause():返回抛出异常的原因。</p><p>e.getMessage():返回异常信息。</p><p>e.printStackTrace():发生异常时，跟踪堆栈信息并输出。</p><p><br></p><p>6、 常异总结</p><p>此部分可以api文档中进行查阅，这里仅做参考。</p><p>常见异常：</p><p>java.lang.IllegalAccessError：违法访问错误。当一个应用试图访问、修改某个类的域（Field）或者调用其方法，但是又违反域或方法的可见性声明，则抛出该异常。</p><p>java.lang.InstantiationError：实例化错误。当一个应用试图通过Java的new操作符构造一个抽象类或者接口时抛出该异常.</p><p>java.lang.OutOfMemoryError：内存不足错误。当可用内存不足以让Java虚拟机分配给一个对象时抛出该错误。java.lang.StackOverflowError：堆栈溢出错误。当一个应用递归调用的层次太深而导致堆栈溢出或者陷入死循环时抛出该错误。</p><p>java.lang.ClassCastException：类造型异常。假设有类A和B（A不是B的父类或子类），O是A的实例，那么当强制将O构造为类B的实例时抛出该异常。该异常经常被称为强制类型转换异常。java.lang.ClassNotFoundException：找不到类异常。当应用试图根据字符串形式的类名构造类，而在遍历CLASSPAH之后找不到对应名称的class文件时，抛出该异常。</p><p>java.lang.ArithmeticException：算术条件异常。譬如：整数除零等。java.lang.ArrayIndexOutOfBoundsException：数组索引越界异常。当对数组的索引值为负数或大于等于数组大小时抛出。</p><p>java.lang.IndexOutOfBoundsException：索引越界异常。当访问某个序列的索引值小于0或大于等于序列大小时，抛出该异常。java.lang.InstantiationException：实例化异常。当试图通过newInstance()方法创建某个类的实例，而该类是一个抽象类或接口时，抛出该异常。</p><p>java.lang.NoSuchFieldException：属性不存在异常。当访问某个类的不存在的属性时抛出该异常。java.lang.NoSuchMethodException：方法不存在异常。当访问某个类的不存在的方法时抛出该异常。java.lang.NullPointerException：空指针异常。当应用试图在要求使用对象的地方使用了null时，抛出该异常。譬如：调用null对象的实例方法、访问null对象的属性、计算null对象的长度、使用throw语句抛出null等等。java.lang.NumberFormatException：数字格式异常。当试图将一个String转换为指定的数字类型，而该字符串确不满足数字类型要求的格式时，抛出该异常。</p><p>java.lang.StringIndexOutOfBoundsException：字符串索引越界异常。当使用索引值访问某个字符串中的字符，而该索引值小于0或大于等于序列大小时，抛出该异常。</p><p>其他异常：java.lang.AbstractMethodError：抽象方法错误。当应用试图调用抽象方法时抛出。java.lang.AssertionError：断言错。用来指示一个断言失败的情况。java.lang.ClassCircularityError：类循环依赖错误。在初始化一个类时，若检测到类之间循环依赖则抛出该异常。java.lang.ClassFormatError：类格式错误。当Java虚拟机试图从一个文件中读取Java类，而检测到该文件的内容不符合类的有效格式时抛出。java.lang.Error：错误。是所有错误的基类，用于标识严重的程序运行问题。这些问题通常描述一些不应被应用程序捕获的反常情况。java.lang.ExceptionInInitializerError：初始化程序错误。当执行一个类的静态初始化程序的过程中，发生了异常时抛出。静态初始化程序是指直接包含于类中的static语句段。java.lang.IncompatibleClassChangeError：不兼容的类变化错误。当正在执行的方法所依赖的类定义发生了不兼容的改变时，抛出该异常。一般在修改了应用中的某些类的声明定义而没有对整个应用重新编译而直接运行的情况下，容易引发该错误。java.lang.InternalError：内部错误。用于指示Java虚拟机发生了内部错误。java.lang.LinkageError：链接错误。该错误及其所有子类指示某个类依赖于另外一些类，在该类编译之后，被依赖的类改变了其类定义而没有重新编译所有的类，进而引发错误的情况。java.lang.NoClassDefFoundError：未找到类定义错误。当Java虚拟机或者类装载器试图实例化某个类，而找不到该类的定义时抛出该错误。java.lang.NoSuchFieldError：域不存在错误。当应用试图访问或者修改某类的某个域，而该类的定义中没有该域的定义时抛出该错误。java.lang.NoSuchMethodError：方法不存在错误。当应用试图调用某类的某个方法，而该类的定义中没有该方法的定义时抛出该错误。java.lang.ThreadDeath：线程结束。当调用Thread类的stop方法时抛出该错误，用于指示线程结束。java.lang.UnknownError：未知错误。用于指示Java虚拟机发生了未知严重错误的情况。java.lang.UnsatisfiedLinkError：未满足的链接错误。当Java虚拟机未找到某个类的声明为native方法的本机语言定义时抛出。java.lang.UnsupportedClassVersionError：不支持的类版本错误。当Java虚拟机试图从读取某个类文件，但是发现该文件的主、次版本号不被当前Java虚拟机支持的时候，抛出该错误。java.lang.VerifyError：验证错误。当验证器检测到某个类文件中存在内部不兼容或者安全问题时抛出该错误。java.lang.VirtualMachineError：虚拟机错误。用于指示虚拟机被破坏或者继续执行操作所需的资源不足的情况。java.lang.ArrayStoreException：数组存储异常。当向数组中存放非数组声明类型对象时抛出。java.lang.CloneNotSupportedException：不支持克隆异常。当没有实现Cloneable接口或者不支持克隆方法时,调用其clone()方法则抛出该异常。java.lang.EnumConstantNotPresentException：枚举常量不存在异常。当应用试图通过名称和枚举类型访问一个枚举对象，但该枚举对象并不包含常量时，抛出该异常。java.lang.Exception：根异常。用以描述应用程序希望捕获的情况。java.lang.IllegalAccessException：违法的访问异常。当应用试图通过反射方式创建某个类的实例、访问该类属性、调用该类方法，而当时又无法访问类的、属性的、方法的或构造方法的定义时抛出该异常。java.lang.IllegalMonitorStateException：违法的监控状态异常。当某个线程试图等待一个自己并不拥有的对象（O）的监控器或者通知其他线程等待该对象（O）的监控器时，抛出该异常。java.lang.IllegalStateException：违法的状态异常。当在Java环境和应用尚未处于某个方法的合法调用状态，而调用了该方法时，抛出该异常。java.lang.IllegalThreadStateException：违法的线程状态异常。当县城尚未处于某个方法的合法调用状态，而调用了该方法时，抛出异常。java.lang.InterruptedException：被中止异常。当某个线程处于长时间的等待、休眠或其他暂停状态，而此时其他的线程通过Thread的interrupt方法终止该线程时抛出该异常。java.lang.NegativeArraySizeException：数组大小为负值异常。当使用负数大小值创建数组时抛出该异常。java.lang.SecurityException：安全异常。由安全管理器抛出，用于指示违反安全情况的异常。java.lang.TypeNotPresentException：类型不存在异常。</p><p>点点关注</p></div><div class="post-meta meta-tags"><ul class=clearfix><li><a>'Java','中异常','体系'</a></li></ul></div></article></div></div><div id=secondary><section class=widget><form id=search action=//www.google.com/search method=get accept-charset=utf-8 target=_blank _lpchecked=1><input type=text name=q maxlength=20 placeholder=搜索>
<input type=hidden name=sitesearch value=geekbank.cf>
<button type=submit>🔍</button></form></section><section class=widget><h3 class=widget-title>最新文章 ⚡</h3><ul class=widget-list></ul></section><section class=widget><h3 class=widget-title>其他</h3><ul class=widget-list><li><a href=TOS.html>使用條款</a></li><li><a href=CommentPolicy.html>留言政策</a></li><li><a href=mailto:gdnews@tuta.io rel=nofollow>DMCA</a></li><li><a href=mailto:gdnews@tuta.io rel=nofollow>聯絡我們</a></li></ul></section></div></div></div></div><footer id=footer><div class=container>&copy; 2020 <a href>极客快訊</a></div></footer><script type=text/javascript>window.MathJax={tex2jax:{inlineMath:[['$','$']],processEscapes:true}};</script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML" async></script><a id=rocket href=#top></a><script type=text/javascript src=https://kknews.cf/js/totop.js async></script><script type=application/javascript>var doNotTrack=false;if(!doNotTrack){window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;ga('create','UA-146415161-2','auto');ga('send','pageview');}</script><script async src=https://www.google-analytics.com/analytics.js></script><script type=text/javascript src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5e508ed9e4e698bb"></script></body></html>