<!doctype html><html lang=tw><head><meta charset=utf-8><meta http-equiv=x-ua-compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1"><meta name=referrer content="no-referrer"><link rel=dns-prefetch href=https://i.geekbank.cf/><title>Python異常處理（二十六） | 极客快訊</title><meta property="og:title" content="Python異常處理（二十六） - 极客快訊"><meta property="og:type" content="article"><meta property="og:locale" content="tw"><meta property="og:image" content="https://p1.pstatp.com/large/pgc-image/b042ebd0bbf644a2b82bf1b115e79517"><link rel=alternate hreflang=x-default href=https://geekbank.cf/tw/%e7%a7%91%e6%8a%80/b290700d.html><link rel=alternate hreflang=zh-tw href=https://geekbank.cf/tw/%e7%a7%91%e6%8a%80/b290700d.html><link rel=alternate hreflang=zh-cn href=https://geekbank.cf/cn/%e7%a7%91%e6%8a%80/b290700d.html><link rel=alternate hreflang=zh-hk href=https://geekbank.cf/tw/%e7%a7%91%e6%8a%80/b290700d.html><link rel=alternate hreflang=zh-mo href=https://geekbank.cf/tw/%e7%a7%91%e6%8a%80/b290700d.html><link rel=alternate hreflang=zh-my href=https://geekbank.cf/cn/%e7%a7%91%e6%8a%80/b290700d.html><link rel=alternate hreflang=zh-sg href=https://geekbank.cf/cn/%e7%a7%91%e6%8a%80/b290700d.html><link rel=canonical href=https://geekbank.cf/tw/%e7%a7%91%e6%8a%80/b290700d.html><meta property="article:published_time" content="2020-11-14T21:03:15+08:00"><meta property="article:modified_time" content="2020-11-14T21:03:15+08:00"><meta name=Keywords content><meta name=description content="Python異常處理（二十六）"><meta name=author content="极客快訊"><meta property="og:url" content="/tw/%E7%A7%91%E6%8A%80/b290700d.html"><link rel=apple-touch-icon sizes=180x180 href=../../apple-touch-icon.png><link rel=icon type=image/png sizes=32x32 href=../../favicon-32x32.png><link rel=icon type=image/png sizes=16x16 href=../../favicon-16x16.png><link rel=manifest href=../../site.webmanifest><link rel=mask-icon href=../../safari-pinned-tab.svg color=#5bbad5><meta name=msapplication-TileColor content="#ffc40d"><meta name=theme-color content="#ffffff"><link rel=stylesheet href=https://geekbank.cf/css/normalize.css><link rel=stylesheet href=https://geekbank.cf/css/style.css><script type=text/javascript src=https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js></script><script type=text/javascript src=https://geekbank.cf/js/jqthumb.min.js></script><script data-ad-client=ca-pub-3525055026201463 async src=https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js></script></head><body><header id=header class=clearfix><div class=container><div class=col-group><div class=site-name><h1><a id=logo href>🤓 极客快訊 Geek Bank</a></h1><p class=description>為你帶來最全的科技知識 🧡</p></div><div><nav id=nav-menu class=clearfix><a class=current href>猜你喜歡</a>
<a href=../../tw/categories/%E7%A7%91%E6%8A%80.html title=科技>科技</a>
<a href=../../tw/categories/%E9%81%8A%E6%88%B2.html title=遊戲>遊戲</a>
<a href=../../tw/categories/%E7%A7%91%E5%AD%B8.html title=科學>科學</a></nav></div></div></div></header><div id=body><div class=container><div class=col-group><div class=col-8 id=main><div class=res-cons><article class=post><header><h1 class=post-title>Python異常處理（二十六）</h1></header><date class="post-meta meta-date">2020-11-14</date><div class=post-meta><span>|</span>
<span class=meta-category><a href=tw/categories/%E7%A7%91%E6%8A%80.html>科技</a></span></div><div class=post-content><div><div class=pgc-img><img alt=Python異常處理（二十六） onerror=errorimg.call(this); src=https://p1.pstatp.com/large/pgc-image/b042ebd0bbf644a2b82bf1b115e79517><p class=pgc-img-caption></p></div><p>Python提供了兩個非常重要的功能來處理Python程序中的異常和錯誤，並在其中添加調試的函數功能 -</p><ul><li>異常處理 - 在本教程中介紹。這是一個列表標準Python中提供的異常 - 標準異常。</li><li>斷言 - 在<em>Python 3</em>教程中的斷言中介紹。</li></ul><p>標準異常</p><p>以下是Python中可用的標準異常列表 -</p><div class=pgc-img><img alt=Python異常處理（二十六） onerror=errorimg.call(this); src=https://p1.pstatp.com/large/pgc-image/26d7ab6abae241c286a932c142c68231><p class=pgc-img-caption></p></div><p>Python中的斷言</p><p>斷言是一個健全檢查，可以在完成對程序的測試後打開或關閉。</p><ul><li>試想斷言的最簡單的方法就是將它與一個raise-if語句(或者更準確的說是一個加註if語句)相對應。測試表達式，如果結果為false，則會引發異常。</li><li>斷言由版本1.5引入的assert語句來執行，它是Python的最新關鍵字。</li><li>程序員經常在函數開始時放置斷言來檢查有效的輸入，並在函數調用後檢查有效的輸出。</li></ul><p>assert語句</p><p>當它遇到一個assert語句時，Python會評估求值它的的表達式，是否為所希望的那樣。 如果表達式為false，Python會引發AssertionError異常。</p><p>assert的語法是 -</p><pre>assert Expression[, Arguments]</pre><p>如果斷言失敗，Python將使用ArgumentExpression作為AssertionError的參數。 使用try-except語句可以像任何其他異常一樣捕獲和處理AssertionError異常。 如果沒有處理，它們將終止程序併產生回溯。</p><p><strong>示例</strong></p><p>這裡將實現一個功能：將給定的溫度從開爾文轉換為華氏度。如果是負溫度，該功能將退出 -</p><pre>#!/usr/bin/python3def KelvinToFahrenheit(Temperature): assert (Temperature &gt;= 0),"Colder than absolute zero!" return ((Temperature-273)*1.8)+32print (KelvinToFahrenheit(273))print (int(KelvinToFahrenheit(505.78)))print (KelvinToFahrenheit(-5))</pre><p>當執行上述代碼時，會產生以下結果 -</p><pre>32.0451Traceback (most recent call last):File "test.py", line 9, in &lt;module&gt;print KelvinToFahrenheit(-5)File "test.py", line 4, in KelvinToFahrenheitassert (Temperature &gt;= 0),"Colder than absolute zero!"AssertionError: Colder than absolute zero!</pre><p>什麼是異常？</p><p>一個例外是在程序執行期間發生的一個事件，它破壞程序指令的正常流程。 一般來說，當Python腳本遇到無法應對的情況時，會引發異常。異常是一個表示錯誤的Python對象。</p><p>當Python腳本引發異常時，它必須立即處理異常，否則終止並退出。</p><p>處理異常</p><p>如果有一些可能引發異常的可疑代碼，可以通過將可疑代碼放在try:塊中來保護您的程序。 在try:塊之後，包括一個except:語句，然後是一個儘可能優雅地處理問題的代碼塊。</p><p><strong>語法</strong></p><p>下面是簡單的語法try .... except ... else塊 -</p><pre>try: You do your operations here ......................except ExceptionI: If there is ExceptionI, then execute this block.except ExceptionII: If there is ExceptionII, then execute this block. ......................else: If there is no exception then execute this block.</pre><p>以下是上述語法的幾個重點 -</p><ul><li>一個try語句可以有多個except語句。 當try塊包含可能引發不同類型的異常的語句時，這就很有用。</li><li>還可以提供一個通用的except子句，它處理任何異常。</li><li>在except子句之後，可以包含一個else子句。 如果try:block中的代碼不引發異常，則else塊中的代碼將執行。</li><li>else-block是一個不需要try:block保護的代碼的地方。</li></ul><p><strong>示例</strong></p><p>此示例打開一個文件，將內容寫入文件，並且優雅地出現，因為完全沒有問題 -</p><pre>#!/usr/bin/python3try: fh = open("testfile", "w") fh.write("This is my test file for exception handling!!")except IOError: print ("Error: can\'t find file or read data")else: print ("Written content in the file successfully") fh.close()</pre><p>這產生以下結果 -</p><pre>Written content in the file successfully</pre><p><strong>示例</strong></p><p>此示例嘗試打開一個沒有寫入權限的文件，因此它引發了一個異常 -</p><pre>#!/usr/bin/python3try: fh = open("testfile", "r") fh.write("This is my test file for exception handling!!")except IOError: print ("Error: can\'t find file or read data")else: print ("Written content in the file successfully")</pre><p>這產生以下結果 -</p><pre>Error: can't find file or read data</pre><p>except子句沒有指定異常</p><p>也可以使用except語句，但不定義異常，如下所示 -</p><pre>try: You do your operations here ......................except: If there is any exception, then execute this block. ......................else: If there is no exception then execute this block.</pre><p>這種try-except語句捕獲所有發生的異常。使用這種try-except語句不被認為是一個很好的編程實踐，因為它捕獲所有異常，但不會讓程序員能更好地識別發生的問題的根本原因。</p><p>except子句指定多個異常</p><p>還可以使用相同的except語句來處理多個異常，如下所示：</p><pre>try: You do your operations here ......................except(Exception1[, Exception2[,...ExceptionN]]]): If there is any exception from the given exception list,  then execute this block. ......................else: If there is no exception then execute this block.</pre><p>try-finally子句</p><p>可以使用finally：塊和try：塊。 finally：塊是放置必須執行代碼的地方，無論try塊是否引發異常。 try-finally語句的語法是這樣的 -</p><pre>try: You do your operations here; ...................... Due to any exception, this may be skipped.finally: This would always be executed. ......................</pre><blockquote><p>注意 - 可以提供except子句或finally子句，但不能同時提供。不能使用else子句以及finally子句。</p></blockquote><p><strong>示例</strong></p><pre>#!/usr/bin/python3try: fh = open("testfile", "w") fh.write("This is my test file for exception handling!!")finally: print ("Error: can\'t find file or read data") fh.close()</pre><p>如果沒有以寫入形式打開文件的權限，則會產生以下結果 -</p><pre>Error: can't find file or read data</pre><p>同樣的例子可以寫得更乾淨如下 -</p><pre>#!/usr/bin/python3try: fh = open("testfile", "w") try: fh.write("This is my test file for exception handling!!") finally: print ("Going to close the file") fh.close()except IOError: print ("Error: can\'t find file or read data")</pre><p>當try塊中拋出異常時，執行將立即傳遞給finally塊。 在finally塊中的所有語句都被執行之後，異常被再次引發，如果存在於try-except語句的下一個更高的層中，則在except語句中處理異常。</p><p>異常參數</p><p>一個異常可以有一個參數，參數它是一個值，它提供有關該問題的其他信息。 參數的內容因異常而異。 可以通過在except子句中提供變量來捕獲異常的參數，如下所示：</p><pre>try: You do your operations here ......................except ExceptionType as Argument: You can print value of Argument here...</pre><p>如果編寫代碼來處理單個異常，則可以在except語句中使用一個變量後跟異常的名稱。 如果要捕獲多個異常，可以使用一個變量後跟隨異常的元組。</p><p>此變量接收大部分包含異常原因的異常值。 變量可以以元組的形式接收單個值或多個值。 該元組通常包含錯誤字符串，錯誤編號和錯誤位置。</p><p><strong>示例</strong></p><p>以下是一個例外 -</p><pre>#!/usr/bin/python3# Define a function here.def temp_convert(var): try: return int(var) except ValueError as Argument: print ("The argument does not contain numbers\n", Argument)# Call above function here.temp_convert("xyz")</pre><p>這產生以下結果 -</p><pre>The argument does not contain numbersinvalid literal for int() with base 10: 'xyz'</pre><p>拋出異常</p><p>可以通過使用raise語句以多種方式引發異常。raise語句的一般語法如下 -</p><p><strong>語法</strong></p><pre>raise [Exception [, args [, traceback]]]</pre><p>這裡，Exception是異常的類型(例如，NameError)，args是異常參數的值。 參數是可選的; 如果沒有提供，則異常參數為None。</p><p>最後一個參數traceback也是可選的(在實踐中很少使用)，如果存在，則是用於異常的追溯對象。</p><p><strong>示例</strong></p><p>異常可以是字符串，類或對象。 Python核心引發的大多數異常都是類，一個參數是類的一個實例。 定義新的例外是非常容易的，可以做到如下 -</p><pre>def functionName( level ): if level &lt;1: raise Exception(level) # The code below to this would not be executed # if we raise the exception return level</pre><blockquote><p>注意 - 為了捕獲異常，“except”子句必須引用與類對象或簡單字符串相同的異常。例如，為了捕獲上述異常，必須寫出except子句如下：</p></blockquote><pre>try: Business Logic here...except Exception as e: Exception handling here using e.args...else: Rest of the code here...</pre><p>以下示例說明了使用引發異常 -</p><pre>#!/usr/bin/python3def functionName( level ): if level &lt;1: raise Exception(level) # The code below to this would not be executed # if we raise the exception return leveltry: l = functionName(-10) print ("level = ",l)except Exception as e: print ("error in level argument",e.args[0])</pre><p>這將產生以下結果 -</p><pre>error in level argument -10</pre><p>用戶定義的異常</p><p>Python還允許通過從標準內置異常導出類來創建自己的異常。</p><p>這是一個與RuntimeError有關的示例。 在這裡，從RuntimeError類創建一個子類。 當需要在捕獲異常時顯示更多具體信息時，這就很有用了。</p><p>在try塊中，用戶定義的異常被引發並被捕獲在except塊中。 變量e用於創建Networkerror類的實例。</p><pre>class Networkerror(RuntimeError): def __init__(self, arg): self.args = arg</pre><p>所以當定義了上面的類以後，就可以使用以下命令拋出異常 -</p><pre>try: raise Networkerror("Bad hostname")except Networkerror,e: print e.args</pre></div></div><div class="post-meta meta-tags"><ul class=clearfix><li><a>Python</a></li><li><a>異常</a></li><li><a>處理</a></li></ul></div></article></div></div><div id=secondary><section class=widget><form id=search action=//www.google.com/search method=get accept-charset=utf-8 target=_blank _lpchecked=1><input type=text name=q maxlength=20 placeholder=搜索>
<input type=hidden name=sitesearch value=geekbank.cf>
<button type=submit>🔍</button></form></section><section class=widget><h3 class=widget-title>最新文章 ⚡</h3><ul class=widget-list><li><a href=../../tw/%E7%A7%91%E6%8A%80/12d49a9e.html alt="一文讀懂 Java 異常處理" class="image featured" style=display:block;margin-left:auto;margin-right:auto;width:100%><img src=https://p3.pstatp.com/large/pgc-image/6c395510d4e245a19bf9cdde6dd9ac2e style=border-radius:25px></a>
<a href=../../tw/%E7%A7%91%E6%8A%80/12d49a9e.html title="一文讀懂 Java 異常處理">一文讀懂 Java 異常處理</a></li><hr><li><a href=../../tw/%E7%A7%91%E6%8A%80/22ac7ff2.html alt=異常-程序員的硬傷，一文教你如何處理 class="image featured" style=display:block;margin-left:auto;margin-right:auto;width:100%><img src=https://p3.pstatp.com/large/dfic-imagehandler/4c4f6d21-cb5a-4ddf-b1b1-5f6edcc374b4 style=border-radius:25px></a>
<a href=../../tw/%E7%A7%91%E6%8A%80/22ac7ff2.html title=異常-程序員的硬傷，一文教你如何處理>異常-程序員的硬傷，一文教你如何處理</a></li><hr><li><a href=../../tw/%E7%A7%91%E6%8A%80/2d47da66.html alt=一起斷路器控制迴路異常的處理及分析 class="image featured" style=display:block;margin-left:auto;margin-right:auto;width:100%><img src=https://p1.pstatp.com/large/pgc-image/4571b3e7966345438fb2fd3b7e8b3390 style=border-radius:25px></a>
<a href=../../tw/%E7%A7%91%E6%8A%80/2d47da66.html title=一起斷路器控制迴路異常的處理及分析>一起斷路器控制迴路異常的處理及分析</a></li><hr><li><a href=../../tw/%E7%A7%91%E6%8A%80/694ad30e.html alt=Python小白必知：文件處理與輸入輸出 class="image featured" style=display:block;margin-left:auto;margin-right:auto;width:100%><img src style=border-radius:25px></a>
<a href=../../tw/%E7%A7%91%E6%8A%80/694ad30e.html title=Python小白必知：文件處理與輸入輸出>Python小白必知：文件處理與輸入輸出</a></li><hr><li><a href=../../tw/%E7%A7%91%E6%8A%80/3eb361a.html alt=Python小技巧：3個處理文件路徑的簡單方法 class="image featured" style=display:block;margin-left:auto;margin-right:auto;width:100%><img src=https://p3.pstatp.com/large/pgc-image/RXfpIwbEJgChY1 style=border-radius:25px></a>
<a href=../../tw/%E7%A7%91%E6%8A%80/3eb361a.html title=Python小技巧：3個處理文件路徑的簡單方法>Python小技巧：3個處理文件路徑的簡單方法</a></li><hr><li><a href=../../tw/%E7%A7%91%E6%8A%80/d49dea5.html alt=生產線異常處理與管理培訓資料 class="image featured" style=display:block;margin-left:auto;margin-right:auto;width:100%><img src=https://p1.pstatp.com/large/pgc-image/f8ce6622a887413586b1f57b7664e827 style=border-radius:25px></a>
<a href=../../tw/%E7%A7%91%E6%8A%80/d49dea5.html title=生產線異常處理與管理培訓資料>生產線異常處理與管理培訓資料</a></li><hr><li><a href=../../tw/%E7%A7%91%E6%8A%80/fabfcd8.html alt=Python辦公自動化｜批量處理文件，一學就會 class="image featured" style=display:block;margin-left:auto;margin-right:auto;width:100%><img src=https://p3.pstatp.com/large/pgc-image/dacb0c1ca5cc446b8b74d8c95bc3d611 style=border-radius:25px></a>
<a href=../../tw/%E7%A7%91%E6%8A%80/fabfcd8.html title=Python辦公自動化｜批量處理文件，一學就會>Python辦公自動化｜批量處理文件，一學就會</a></li><hr><li><a href=../../tw/%E7%A7%91%E6%8A%80/fc520d9.html alt=用Python實現批量高效文件處理，解放你的雙手 class="image featured" style=display:block;margin-left:auto;margin-right:auto;width:100%><img src=https://p1.pstatp.com/large/pgc-image/6a8aade78d34491189c3149331390715 style=border-radius:25px></a>
<a href=../../tw/%E7%A7%91%E6%8A%80/fc520d9.html title=用Python實現批量高效文件處理，解放你的雙手>用Python實現批量高效文件處理，解放你的雙手</a></li><hr><li><a href=../../tw/%E9%81%8A%E6%88%B2/7b7b650.html alt=Python數據處理：五分鐘搞定異常值和重複值 class="image featured" style=display:block;margin-left:auto;margin-right:auto;width:100%><img src=http://p1.pstatp.com/large/pgc-image/1c8aef2db0884250a7268ec089f7ad4b style=border-radius:25px></a>
<a href=../../tw/%E9%81%8A%E6%88%B2/7b7b650.html title=Python數據處理：五分鐘搞定異常值和重複值>Python數據處理：五分鐘搞定異常值和重複值</a></li><hr><li><a href=../../tw/%E7%A7%91%E6%8A%80/f03a5d3.html alt=變壓器異常處理方法 class="image featured" style=display:block;margin-left:auto;margin-right:auto;width:100%><img src style=border-radius:25px></a>
<a href=../../tw/%E7%A7%91%E6%8A%80/f03a5d3.html title=變壓器異常處理方法>變壓器異常處理方法</a></li><hr><li><a href=../../tw/%E7%A7%91%E6%8A%80/d2d681b6.html alt=中超賽場異常火爆，賽後場面陷入一片混亂，數名安保人員驅趕球員 class="image featured" style=display:block;margin-left:auto;margin-right:auto;width:100%><img src=https://p1.pstatp.com/large/pgc-image/c6d14dc62de74f24afb5dfefc3a2ee52 style=border-radius:25px></a>
<a href=../../tw/%E7%A7%91%E6%8A%80/d2d681b6.html title=中超賽場異常火爆，賽後場面陷入一片混亂，數名安保人員驅趕球員>中超賽場異常火爆，賽後場面陷入一片混亂，數名安保人員驅趕球員</a></li><hr><li><a href=../../tw/%E7%A7%91%E6%8A%80/cd064e23.html alt=掌上生活“異常登錄5702”招行阻擋羊毛黨或存“誤傷” class="image featured" style=display:block;margin-left:auto;margin-right:auto;width:100%><img src=https://p3.pstatp.com/large/pgc-image/RrZPeex25JpWHz style=border-radius:25px></a>
<a href=../../tw/%E7%A7%91%E6%8A%80/cd064e23.html title=掌上生活“異常登錄5702”招行阻擋羊毛黨或存“誤傷”>掌上生活“異常登錄5702”招行阻擋羊毛黨或存“誤傷”</a></li><hr><li><a href=../../tw/%E7%A7%91%E6%8A%80/91eece92.html alt="只需 45 秒，Python 給故宮畫一組手繪圖！" class="image featured" style=display:block;margin-left:auto;margin-right:auto;width:100%><img src=https://p3.pstatp.com/large/pgc-image/df1bd890ffee4a439e9f5142ae42c102 style=border-radius:25px></a>
<a href=../../tw/%E7%A7%91%E6%8A%80/91eece92.html title="只需 45 秒，Python 給故宮畫一組手繪圖！">只需 45 秒，Python 給故宮畫一組手繪圖！</a></li><hr><li><a href=../../tw/%E7%A7%91%E6%8A%80/8aab963e.html alt=Python手繪圖瞭解一下！ class="image featured" style=display:block;margin-left:auto;margin-right:auto;width:100%><img src=https://p1.pstatp.com/large/pgc-image/746c9e6e214b48b2a0215fc9e151cdc8 style=border-radius:25px></a>
<a href=../../tw/%E7%A7%91%E6%8A%80/8aab963e.html title=Python手繪圖瞭解一下！>Python手繪圖瞭解一下！</a></li><hr><li><a href=../../tw/%E7%A7%91%E6%8A%80/cfd854c6.html alt=故宮下雪了！我用Python給它畫了一組手繪圖，僅用45秒（附代碼） class="image featured" style=display:block;margin-left:auto;margin-right:auto;width:100%><img src=https://p1.pstatp.com/large/pgc-image/774d2f0a372f48c589ec84dd3a164dd9 style=border-radius:25px></a>
<a href=../../tw/%E7%A7%91%E6%8A%80/cfd854c6.html title=故宮下雪了！我用Python給它畫了一組手繪圖，僅用45秒（附代碼）>故宮下雪了！我用Python給它畫了一組手繪圖，僅用45秒（附代碼）</a></li><hr></ul></section><section class=widget><h3 class=widget-title>其他</h3><ul class=widget-list><li><a href=TOS.html>使用條款</a></li><li><a href=CommentPolicy.html>留言政策</a></li><li><a href=mailto:gdnews@tuta.io rel=nofollow>DMCA</a></li><li><a href=mailto:gdnews@tuta.io rel=nofollow>聯絡我們</a></li></ul></section></div></div></div></div><footer id=footer><div class=container>&copy; 2020 <a href>极客快訊</a></div></footer><script type=text/javascript>window.MathJax={tex2jax:{inlineMath:[['$','$']],processEscapes:true}};</script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML" async></script><a id=rocket href=#top></a><script type=text/javascript src=https://kknews.cf/js/totop.js async></script><script type=text/javascript src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5e508ed9e4e698bb"></script></body></html>